export type RouterToolkit = "googlesuper" | "github";

export type RouterIntent = {
  id: string;
  domain: "email" | "calendar" | "contacts" | "github" | "drive" | "sheet";
  description: string;
  toolSlugs: string[];
  requiredToolkits: RouterToolkit[];
  mutating: boolean;
  keywords: string[];
  examplePrompts: string[];
  companionIntentIds?: string[];
};

export const ROUTER_INTENTS: RouterIntent[] = [
  {
    id: "email.read_summary",
    domain: "email",
    description: "Read, search, scan, or summarize recent Gmail messages and important inbox items.",
    toolSlugs: ["GOOGLESUPER_FETCH_EMAILS", "GOOGLESUPER_FETCH_MESSAGE_BY_MESSAGE_ID"],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "read email",
      "read emails",
      "fetch emails",
      "show emails",
      "scan emails",
      "summarize emails",
      "summarize inbox",
      "recent emails",
      "latest emails",
      "last emails",
      "important emails",
      "gmail",
      "inbox",
      "messages",
    ],
    examplePrompts: [
      "Read my last 100 emails and show me the important ones.",
      "Summarize my recent Gmail messages.",
      "Scan my latest inbox messages for anything important.",
      "Show me the important emails from today.",
    ],
  },
  {
    id: "email.purchase_history",
    domain: "email",
    description: "Find purchases, orders, receipts, invoices, merchants, or products bought from email.",
    toolSlugs: [
      "GOOGLESUPER_FETCH_EMAILS",
      "GOOGLESUPER_FETCH_MESSAGE_BY_MESSAGE_ID",
      "GOOGLESUPER_GET_CURRENT_DATE_TIME",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "bought",
      "buy",
      "purchase",
      "purchased",
      "order",
      "orders",
      "receipt",
      "receipts",
      "invoice",
      "invoices",
      "merchant",
      "vendor",
      "store",
      "seller",
      "products",
      "items",
      "past month",
      "last month",
      "last week",
    ],
    examplePrompts: [
      "What products have I bought from Scentoria in the past month?",
      "Find my Amazon receipts from last week.",
      "List orders from Nike in my email.",
      "Show me invoices from Stripe this month.",
    ],
  },
  {
    id: "email.send",
    domain: "email",
    description: "Send, compose, draft, reply to, or forward an email.",
    toolSlugs: ["GOOGLESUPER_SEND_EMAIL", "GOOGLESUPER_GET_CONTACTS"],
    requiredToolkits: ["googlesuper"],
    mutating: true,
    keywords: [
      "send email",
      "compose email",
      "draft email",
      "reply email",
      "forward email",
      "email to",
      "mail to",
      "send message",
      "write email",
    ],
    examplePrompts: [
      "Send an email to Karan.",
      "Compose an email to my manager.",
      "Draft a message to Priya about the meeting.",
      "Reply to this email politely.",
    ],
  },
  {
    id: "email.send_with_upload",
    domain: "email",
    description: "Send an email with an uploaded or attached PDF, file, document, or resume.",
    toolSlugs: ["GOOGLESUPER_SEND_EMAIL", "GOOGLESUPER_GET_CONTACTS"],
    requiredToolkits: ["googlesuper"],
    mutating: true,
    keywords: [
      "attached pdf",
      "attached file",
      "uploaded pdf",
      "uploaded document",
      "uploaded file",
      "with attachment",
      "with attached",
      "attach pdf",
      "send attached",
      "email attached",
      "send email attachment",
    ],
    examplePrompts: [
      "Send an email with the attached pdf.",
      "Email this uploaded document to Karan.",
      "Send the attached resume to the recruiter.",
      "Compose an email and attach the uploaded PDF.",
    ],
  },
  {
    id: "email.find_attachment",
    domain: "email",
    description: "Find, inspect, download, or read attachments from existing Gmail messages.",
    toolSlugs: [
      "GOOGLESUPER_FETCH_EMAILS",
      "GOOGLESUPER_FETCH_MESSAGE_BY_MESSAGE_ID",
      "GOOGLESUPER_GET_ATTACHMENT",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "email attachment",
      "gmail attachment",
      "download attachment",
      "find attachment",
      "get attachment",
      "attachment from email",
      "attached to email",
      "email pdf",
    ],
    examplePrompts: [
      "Find the PDF attached to my latest email from HR.",
      "Download the attachment from an email.",
      "Read the document attached to a Gmail message.",
      "Get the invoice attachment from yesterday's email.",
    ],
  },
  {
    id: "calendar.schedule",
    domain: "calendar",
    description: "Create or schedule calendar events, meetings, invites, calls, and find availability.",
    toolSlugs: [
      "GOOGLESUPER_CREATE_EVENT",
      "GOOGLESUPER_FIND_FREE_SLOTS",
      "GOOGLESUPER_EVENTS_LIST",
      "GOOGLESUPER_GET_CONTACTS",
      "GOOGLESUPER_SEARCH_PEOPLE",
      "GOOGLESUPER_GET_CURRENT_DATE_TIME",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: true,
    keywords: [
      "schedule",
      "calendar event",
      "create event",
      "meeting",
      "book meeting",
      "calendar invite",
      "invite",
      "free slot",
      "availability",
      "tomorrow",
      "call",
    ],
    examplePrompts: [
      "Schedule a calendar event tomorrow with Karan.",
      "Book a meeting with Priya next week.",
      "Find a free slot with my team and create an invite.",
      "Create a calendar event for tomorrow afternoon.",
    ],
  },
  {
    id: "calendar.read",
    domain: "calendar",
    description: "Read calendar events, agendas, upcoming meetings, and schedules.",
    toolSlugs: ["GOOGLESUPER_EVENTS_LIST", "GOOGLESUPER_GET_CURRENT_DATE_TIME"],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "calendar",
      "agenda",
      "events",
      "upcoming meetings",
      "today's meetings",
      "tomorrow's meetings",
      "list events",
      "my schedule",
    ],
    examplePrompts: [
      "What is on my calendar today?",
      "Show my agenda for tomorrow.",
      "List my upcoming meetings this week.",
      "What events do I have later today?",
    ],
  },
  {
    id: "contacts.lookup",
    domain: "contacts",
    description: "Find contacts, people, or email addresses.",
    toolSlugs: ["GOOGLESUPER_GET_CONTACTS", "GOOGLESUPER_SEARCH_PEOPLE"],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "contact",
      "contacts",
      "person",
      "people",
      "email address",
      "find email",
      "lookup contact",
      "search people",
    ],
    examplePrompts: [
      "Find Karan in my contacts.",
      "What is Priya's email address?",
      "Search people named Aman.",
      "Look up this contact for me.",
    ],
  },
  {
    id: "github.issues_read",
    domain: "github",
    description: "Read, search, list, inspect, or summarize GitHub issues and pull requests.",
    toolSlugs: [
      "GITHUB_LIST_REPOSITORY_ISSUES",
      "GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS",
      "GITHUB_GET_AN_ISSUE",
    ],
    requiredToolkits: ["github"],
    mutating: false,
    keywords: [
      "github",
      "repo",
      "repository",
      "issue",
      "issues",
      "pull request",
      "pull requests",
      "pr",
      "open issues",
      "closed issues",
      "all issues",
      "list issues",
      "search issues",
    ],
    examplePrompts: [
      "Read all issues on composiohq/composio.",
      "Summarize open and closed GitHub issues.",
      "Search pull requests in this repository.",
      "List the problems reported in repo issues.",
    ],
  },
  {
    id: "github.issues_to_sheet",
    domain: "github",
    description: "Read GitHub issues or pull requests and create a Google Sheet report of the problems.",
    toolSlugs: [
      "GITHUB_LIST_REPOSITORY_ISSUES",
      "GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS",
      "GITHUB_GET_AN_ISSUE",
      "GOOGLESUPER_SHEET_FROM_JSON",
      "GOOGLESUPER_SPREADSHEETS_VALUES_APPEND",
    ],
    requiredToolkits: ["github", "googlesuper"],
    mutating: true,
    keywords: [
      "github sheet",
      "issues sheet",
      "issue report",
      "repo issues sheet",
      "google sheet",
      "spreadsheet",
      "export issues",
      "problems people are reporting",
      "open and closed",
      "all issues",
      "make a sheet",
      "composiohq/composio",
    ],
    examplePrompts: [
      "Read all the issues open and closed on composiohq/composio and make a Google Sheet with the problems people are reporting.",
      "Export repository issues to a spreadsheet.",
      "Create a sheet summarizing GitHub issue reports.",
      "Make a Google Sheet from all repo issues.",
    ],
  },
  {
    id: "drive.find",
    domain: "drive",
    description: "Find or list Google Drive files and folders from names or Drive URLs.",
    toolSlugs: [
      "GOOGLESUPER_FIND_FILE",
      "GOOGLESUPER_FIND_FOLDER",
      "GOOGLESUPER_LIST_CHILDREN_V2",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "drive",
      "drive folder",
      "drive file",
      "google drive",
      "folder",
      "file",
      "files",
      "find folder",
      "find file",
      "list folder",
      "drive url",
    ],
    examplePrompts: [
      "Find this folder in Drive.",
      "List the files in this Google Drive folder.",
      "Find a Drive file by name.",
      "Show the children of this Drive folder URL.",
    ],
  },
  {
    id: "drive.documents_extract",
    domain: "drive",
    description: "Download and parse Drive documents, PDFs, resumes, and candidate files.",
    toolSlugs: [
      "GOOGLESUPER_FIND_FILE",
      "GOOGLESUPER_FIND_FOLDER",
      "GOOGLESUPER_LIST_CHILDREN_V2",
      "GOOGLESUPER_DOWNLOAD_FILE",
      "GOOGLESUPER_DOWNLOAD_FILE_OPERATION",
      "GOOGLESUPER_PARSE_FILE",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: false,
    keywords: [
      "drive documents",
      "parse documents",
      "download documents",
      "extract documents",
      "pdf",
      "pdfs",
      "resume",
      "resumes",
      "candidate",
      "candidates",
      "docs",
      "parse files",
    ],
    examplePrompts: [
      "Parse the PDFs in this Drive folder.",
      "Extract text from resumes in Drive.",
      "Download and read candidate documents from Google Drive.",
      "Parse documents from this Drive URL.",
    ],
  },
  {
    id: "drive.resumes_to_sheet",
    domain: "drive",
    description: "Extract all resumes or candidate documents from Drive into a Google Sheet with structured candidate rows.",
    toolSlugs: [
      "GOOGLESUPER_FIND_FOLDER",
      "GOOGLESUPER_FIND_FILE",
      "GOOGLESUPER_LIST_CHILDREN_V2",
      "GOOGLESUPER_DOWNLOAD_FILE",
      "GOOGLESUPER_DOWNLOAD_FILE_OPERATION",
      "GOOGLESUPER_PARSE_FILE",
      "GOOGLESUPER_SHEET_FROM_JSON",
      "GOOGLESUPER_SPREADSHEETS_VALUES_APPEND",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: true,
    keywords: [
      "drive resumes",
      "resumes sheet",
      "candidate sheet",
      "candidate names",
      "university",
      "uni",
      "last job",
      "last company",
      "all resumes",
      "extract candidates",
      "make a google sheet",
      "drive folder",
      "resume spreadsheet",
    ],
    examplePrompts: [
      "Take all the resumes in this Drive and make a Google Sheet with candidate names, uni, and last job.",
      "Extract candidate names, university, and last company from resumes in a Drive folder.",
      "Parse all resume PDFs from Drive into spreadsheet rows.",
      "Make a sheet from all candidate resumes in this Google Drive folder.",
    ],
  },
  {
    id: "sheet.create_or_update",
    domain: "sheet",
    description: "Create a Google Sheet or append structured rows when the source data is already known.",
    toolSlugs: [
      "GOOGLESUPER_SHEET_FROM_JSON",
      "GOOGLESUPER_CREATE_GOOGLE_SHEET1",
      "GOOGLESUPER_SPREADSHEETS_VALUES_APPEND",
    ],
    requiredToolkits: ["googlesuper"],
    mutating: true,
    keywords: [
      "google sheet",
      "spreadsheet",
      "sheet",
      "append rows",
      "write rows",
      "create table",
      "table",
      "csv",
      "rows",
    ],
    examplePrompts: [
      "Make a Google Sheet from this data.",
      "Append these rows to a spreadsheet.",
      "Create a table from the items above.",
      "Write these records into a Google Sheet.",
    ],
  },
];

export const ASSIGNMENT_CRITICAL_INTENT_IDS = [
  "email.read_summary",
  "calendar.schedule",
  "github.issues_to_sheet",
  "drive.resumes_to_sheet",
  "email.send_with_upload",
] as const;
